"""re-add pain column

Revision ID: c5d9a0897e46
Revises: d90af757a7b1
Create Date: 2026-07-23 08:24:34.733801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d9a0897e46'
down_revision: Union[str, Sequence[str], None] = 'd90af757a7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pain', sa.Text(), server_default=sa.text("''"), nullable=False))
        batch_op.drop_index(batch_op.f('idx_training_history_exercise_date'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_training_history_exercise_date'), ['exercise_id', 'date', 'id'], unique=False)
        batch_op.drop_column('pain')

    # ### end Alembic commands ###
